# Generated by Django 5.0.6 on 2024-06-18 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[(0, 'In Process'), (1, 'Pending'), (2, 'Rejected'), (3, 'Aproved')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='report',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='report',
        ),
        migrations.CreateModel(
            name='CapexContractor',
            fields=[
                ('basecontractor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basecontractor')),
            ],
            bases=('api.basecontractor',),
        ),
        migrations.CreateModel(
            name='OpexContractor',
            fields=[
                ('basecontractor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basecontractor')),
            ],
            bases=('api.basecontractor',),
        ),
        migrations.CreateModel(
            name='CapexTransaction',
            fields=[
                ('basetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basetransaction')),
                ('category', models.CharField(choices=[(0, 'Equipment'), (1, 'Buildings'), (2, 'Technology')], max_length=100)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capex_contractor', to='api.capexcontractor')),
                ('user_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_project', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.basetransaction',),
        ),
        migrations.CreateModel(
            name='OpexTransaction',
            fields=[
                ('basetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basetransaction')),
                ('category', models.CharField(choices=[(0, 'Salaries'), (1, 'Utilities'), (2, 'Rent')], max_length=100)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opex_contractor', to='api.opexcontractor')),
                ('user_planner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_planner', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.basetransaction',),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
