# Generated by Django 5.0.6 on 2024-06-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_basecontractor_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapexRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OpexRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='basetransaction',
            name='status',
            field=models.CharField(choices=[('in_process', 'In Process'), ('pending', 'Pending'), ('reject', 'Rejected'), ('aproved', 'Aproved')], max_length=100),
        ),
        migrations.AlterField(
            model_name='capextransaction',
            name='category',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('building', 'Buildings'), ('technology', 'Technology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='opextransaction',
            name='category',
            field=models.CharField(choices=[('salaries', 'Salaries'), ('utilities', 'Utilities'), ('rent', 'Rent')], max_length=100),
        ),
    ]
